name: Python application

on:
  push:
    branches: [ "main" ]  
  pull_request:
    branches: [ "main" ]  

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] 
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest black mypy
        pip install tox==3.24.4
        pip install -r requirements.txt

    - name: Display Python version and installed packages
      run: |
        python --version
        pip list


    - name: Test with tox
      run: tox
      env:
        TOX_ENV: py${{ matrix.python-version }}-${{ matrix.os }}